import bcrypt from 'bcryptjs';

const data = {
  users: [
    {
      name: 'sibusiso',
      email: 'admin@example.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: true,
      slug: 'Sgxfgzdxgzdgxdcfz',
      accounttype: 'buyer'
    },
    {
      name: 'sibusiso',
      email: 'lerato@gmail.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: false,
      slug: 'sGzdzsyhtghgsfxgdxg',

      accounttype: 'expert',

      businessname: 'Leratos Fruits and Veg',
      businesslogo: "https://images.pexels.com/photos/2872755/pexels-photo-2872755.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
      businessbanner: "https://images.pexels.com/photos/2872755/pexels-photo-2872755.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
     
      businessprovince: 'limpopo',
      businesscity: 'polokwane',
      businesslocation: 'moletje',

      product1: "https://images.pexels.com/photos/2872755/pexels-photo-2872755.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
      product2: "https://images.pexels.com/photos/2872755/pexels-photo-2872755.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
      product3: "https://images.pexels.com/photos/2872755/pexels-photo-2872755.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",


      rating: 4.5,
      numReviews: 10, 
    },
    {
      name: 'sibusiso',
      email: 'kevin@gmail.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: false,
      slug: 'sGzdzsgsfxgdxg',

      accounttype: 'supplier',

      businessname: 'Leratos Fruits and Veg',
      businesslogo: "https://images.pexels.com/photos/2872755/pexels-photo-2872755.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
      businessbanner: "https://images.pexels.com/photos/2872755/pexels-photo-2872755.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
     
      businessprovince: 'limpopo',
      businesscity: 'polokwane',
      businesslocation: 'moletje',

      product1: "https://images.pexels.com/photos/2872755/pexels-photo-2872755.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
      product2: "https://images.pexels.com/photos/2872755/pexels-photo-2872755.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
      product3: "https://images.pexels.com/photos/2872755/pexels-photo-2872755.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",


      rating: 4.5,
      numReviews: 10,
    },
  ],
  products: [
     // fruits ,
    {
      // _id: '1',
      name: 'Apples',
      slug: 'apples',
      category: 'fruits',
      image: "https://images.pexels.com/photos/2872755/pexels-photo-2872755.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
      price: 120,
      catalogue: "food",
      countInStock: 10,
      size: '5kg',
      rating: 4.5,
      numReviews: 10,
      city: 'polokwane',
      province: 'limpopo',
      location: 'moletje',
      description: "Introducing our succulent oranges, nature's perfect blend of tangy sweetness and refreshing zest. Bursting with juicy flavor and vibrant color, each handpicked orange promises a delightful sensory experience. Whether enjoyed as a snack, juiced for a refreshing beverage, or incorporated into culinary creations, our premium oranges elevate any occasion with their unparalleled freshness and natural goodness. Taste the sunshine with every bite of our premium oranges.",
    },
    {
      // _id: '1',
      name: 'Bananas',
      slug: 'bananas',
      category: 'fruits',
      image: "https://images.pexels.com/photos/2872755/pexels-photo-2872755.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
      price: 120,
      catalogue: "food",
      countInStock: 10,
      size: '5kg',
      rating: 4.5,
      numReviews: 10,
      city: 'polokwane',
      province: 'limpopo',
      location: 'moletje',
      description: "Introducing our succulent oranges, nature's perfect blend of tangy sweetness and refreshing zest. Bursting with juicy flavor and vibrant color, each handpicked orange promises a delightful sensory experience. Whether enjoyed as a snack, juiced for a refreshing beverage, or incorporated into culinary creations, our premium oranges elevate any occasion with their unparalleled freshness and natural goodness. Taste the sunshine with every bite of our premium oranges.",
    },
    {
      // _id: '1',
      name: 'Oranges',
      slug: 'oranges',
      category: 'fruits',
      image: "https://images.pexels.com/photos/2872755/pexels-photo-2872755.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
      price: 120,
      catalogue: "food",
      countInStock: 10,
      size: '5kg',
      rating: 4.5,
      numReviews: 10,
      city: 'polokwane',
      province: 'limpopo',
      location: 'moletje',
      description: "Introducing our succulent oranges, nature's perfect blend of tangy sweetness and refreshing zest. Bursting with juicy flavor and vibrant color, each handpicked orange promises a delightful sensory experience. Whether enjoyed as a snack, juiced for a refreshing beverage, or incorporated into culinary creations, our premium oranges elevate any occasion with their unparalleled freshness and natural goodness. Taste the sunshine with every bite of our premium oranges.",
    },
    {
      // _id: '1',
      name: 'Grapes',
      slug: 'grapes',
      category: 'fruits',
      image: "https://images.pexels.com/photos/2872755/pexels-photo-2872755.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
      price: 120,
      catalogue: "food",
      countInStock: 10,
      size: '10kg',
      rating: 4.5,
      numReviews: 10,
      city: 'polokwane',
      province: 'limpopo',
      location: 'moletje',
      description: "Introducing our succulent oranges, nature's perfect blend of tangy sweetness and refreshing zest. Bursting with juicy flavor and vibrant color, each handpicked orange promises a delightful sensory experience. Whether enjoyed as a snack, juiced for a refreshing beverage, or incorporated into culinary creations, our premium oranges elevate any occasion with their unparalleled freshness and natural goodness. Taste the sunshine with every bite of our premium oranges.",
    },
    {
      // _id: '1',
      name: 'Mangoes',
      slug: 'mangoes',
      category: 'fruits',
      image: "https://images.pexels.com/photos/2872755/pexels-photo-2872755.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
      price: 120,
      catalogue: "food",
      countInStock: 10,
      size: '10kg',
      rating: 4.5,
      numReviews: 10,
      city: 'polokwane',
      province: 'limpopo',
      location: 'moletje',
      description: "Introducing our succulent oranges, nature's perfect blend of tangy sweetness and refreshing zest. Bursting with juicy flavor and vibrant color, each handpicked orange promises a delightful sensory experience. Whether enjoyed as a snack, juiced for a refreshing beverage, or incorporated into culinary creations, our premium oranges elevate any occasion with their unparalleled freshness and natural goodness. Taste the sunshine with every bite of our premium oranges.",
    },
    {
      // _id: '1',
      name: 'Pineapples',
      slug: 'pineapples',
      category: 'fruits',
      image: "https://images.pexels.com/photos/2872755/pexels-photo-2872755.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
      price: 120,
      catalogue: "food",
      countInStock: 10,
      size: '10kg',
      rating: 4.5,
      numReviews: 10,
      city: 'polokwane',
      province: 'limpopo',
      location: 'moletje',
      description: "Introducing our succulent oranges, nature's perfect blend of tangy sweetness and refreshing zest. Bursting with juicy flavor and vibrant color, each handpicked orange promises a delightful sensory experience. Whether enjoyed as a snack, juiced for a refreshing beverage, or incorporated into culinary creations, our premium oranges elevate any occasion with their unparalleled freshness and natural goodness. Taste the sunshine with every bite of our premium oranges.",
    },
    {
      // _id: '1',
      name: 'Peaches',
      slug: 'peaches',
      category: 'fruits',
      image: "https://images.pexels.com/photos/2872755/pexels-photo-2872755.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
      price: 120,
      catalogue: "food",
      countInStock: 10,
      size: '10kg',
      rating: 4.5,
      numReviews: 10,
      city: 'polokwane',
      province: 'limpopo',
      location: 'moletje',
      description: "Introducing our succulent oranges, nature's perfect blend of tangy sweetness and refreshing zest. Bursting with juicy flavor and vibrant color, each handpicked orange promises a delightful sensory experience. Whether enjoyed as a snack, juiced for a refreshing beverage, or incorporated into culinary creations, our premium oranges elevate any occasion with their unparalleled freshness and natural goodness. Taste the sunshine with every bite of our premium oranges.",
    },
    {
      // _id: '1',
      name: 'Avocados',
      slug: 'avocados',
      category: 'fruits',
      image: "https://images.pexels.com/photos/2872755/pexels-photo-2872755.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
      price: 120,
      catalogue: "food",
      countInStock: 10,
      size: '5kg',
      rating: 4.5,
      numReviews: 10,
      city: 'polokwane',
      province: 'limpopo',
      location: 'moletje',
      description: "Introducing our succulent oranges, nature's perfect blend of tangy sweetness and refreshing zest. Bursting with juicy flavor and vibrant color, each handpicked orange promises a delightful sensory experience. Whether enjoyed as a snack, juiced for a refreshing beverage, or incorporated into culinary creations, our premium oranges elevate any occasion with their unparalleled freshness and natural goodness. Taste the sunshine with every bite of our premium oranges.",
    },
    {
      // _id: '1',
      name: 'Papayas ',
      slug: 'papayas ',
      category: 'fruits',
      image: "https://images.pexels.com/photos/2872755/pexels-photo-2872755.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
      price: 120,
      catalogue: "food",
      countInStock: 10,
      size: '0.9kg',
      rating: 4.5,
      numReviews: 10,
      city: 'polokwane',
      province: 'limpopo',
      location: 'moletje',
      description: "Introducing our succulent oranges, nature's perfect blend of tangy sweetness and refreshing zest. Bursting with juicy flavor and vibrant color, each handpicked orange promises a delightful sensory experience. Whether enjoyed as a snack, juiced for a refreshing beverage, or incorporated into culinary creations, our premium oranges elevate any occasion with their unparalleled freshness and natural goodness. Taste the sunshine with every bite of our premium oranges.",
    },
    {
      // _id: '1',
      name: 'Watermelons',
      slug: 'watermelons',
      category: 'fruits',
      image: "https://images.pexels.com/photos/2872755/pexels-photo-2872755.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
      price: 120,
      catalogue: "food",
      countInStock: 10,
      size: '0.9kg',
      rating: 4.5,
      numReviews: 10,
      city: 'polokwane',
      province: 'limpopo',
      location: 'moletje',
      description: "Introducing our succulent oranges, nature's perfect blend of tangy sweetness and refreshing zest. Bursting with juicy flavor and vibrant color, each handpicked orange promises a delightful sensory experience. Whether enjoyed as a snack, juiced for a refreshing beverage, or incorporated into culinary creations, our premium oranges elevate any occasion with their unparalleled freshness and natural goodness. Taste the sunshine with every bite of our premium oranges.",
    },

     // vegitables ,
     {
      // _id: '1',
      name: 'Tomatoes',
      slug: 'tomatoes',
      category: 'vegitables',
      image: "https://images.pexels.com/photos/2872755/pexels-photo-2872755.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
      price: 120,
      catalogue: "food",
      countInStock: 10,
      size: '0.9kg',
      rating: 4.5,
      numReviews: 10,
      city: 'polokwane',
      province: 'limpopo',
      location: 'moletje',
      description: "Introducing our succulent oranges, nature's perfect blend of tangy sweetness and refreshing zest. Bursting with juicy flavor and vibrant color, each handpicked orange promises a delightful sensory experience. Whether enjoyed as a snack, juiced for a refreshing beverage, or incorporated into culinary creations, our premium oranges elevate any occasion with their unparalleled freshness and natural goodness. Taste the sunshine with every bite of our premium oranges.",
    },
    {
      // _id: '1',
      name: 'Potatoes',
      slug: 'potatoes',
      category: 'vegitables',
      image: "https://images.pexels.com/photos/2872755/pexels-photo-2872755.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
      price: 120,
      catalogue: "food",
      countInStock: 10,
      size: '5kg',
      rating: 4.5,
      numReviews: 10,
      city: 'polokwane',
      province: 'limpopo',
      location: 'moletje',
      description: "Introducing our succulent oranges, nature's perfect blend of tangy sweetness and refreshing zest. Bursting with juicy flavor and vibrant color, each handpicked orange promises a delightful sensory experience. Whether enjoyed as a snack, juiced for a refreshing beverage, or incorporated into culinary creations, our premium oranges elevate any occasion with their unparalleled freshness and natural goodness. Taste the sunshine with every bite of our premium oranges.",
    },
    {
      // _id: '1',
      name: 'Onions',
      slug: 'onions',
      category: 'vegitables',
      image: "https://images.pexels.com/photos/2872755/pexels-photo-2872755.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
      price: 120,
      catalogue: "food",
      countInStock: 10,
      size: '5kg',
      rating: 4.5,
      numReviews: 10,
      city: 'polokwane',
      province: 'limpopo',
      location: 'moletje',
      description: "Introducing our succulent oranges, nature's perfect blend of tangy sweetness and refreshing zest. Bursting with juicy flavor and vibrant color, each handpicked orange promises a delightful sensory experience. Whether enjoyed as a snack, juiced for a refreshing beverage, or incorporated into culinary creations, our premium oranges elevate any occasion with their unparalleled freshness and natural goodness. Taste the sunshine with every bite of our premium oranges.",
    },
    {
      // _id: '1',
      name: 'Carrots',
      slug: 'carrots',
      category: 'vegitables',
      image: "https://images.pexels.com/photos/2872755/pexels-photo-2872755.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
      price: 120,
      catalogue: "food",
      countInStock: 10,
      size: '5kg',
      rating: 4.5,
      numReviews: 10,
      city: 'polokwane',
      province: 'limpopo',
      location: 'moletje',
      description: "Introducing our succulent oranges, nature's perfect blend of tangy sweetness and refreshing zest. Bursting with juicy flavor and vibrant color, each handpicked orange promises a delightful sensory experience. Whether enjoyed as a snack, juiced for a refreshing beverage, or incorporated into culinary creations, our premium oranges elevate any occasion with their unparalleled freshness and natural goodness. Taste the sunshine with every bite of our premium oranges.",
    },
    {
      // _id: '1',
      name: 'Cabbage',
      slug: 'cabbage',
      category: 'vegitables',
      image: "https://images.pexels.com/photos/2872755/pexels-photo-2872755.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
      price: 120,
      catalogue: "food",
      countInStock: 10,
      size: '5kg',
      rating: 4.5,
      numReviews: 10,
      city: 'polokwane',
      province: 'limpopo',
      location: 'moletje',
      description: "Introducing our succulent oranges, nature's perfect blend of tangy sweetness and refreshing zest. Bursting with juicy flavor and vibrant color, each handpicked orange promises a delightful sensory experience. Whether enjoyed as a snack, juiced for a refreshing beverage, or incorporated into culinary creations, our premium oranges elevate any occasion with their unparalleled freshness and natural goodness. Taste the sunshine with every bite of our premium oranges.",
    },
    {
      // _id: '1',
      name: 'Spinach',
      slug: 'spinach',
      category: 'vegitables',
      image: "https://images.pexels.com/photos/2872755/pexels-photo-2872755.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
      price: 120,
      catalogue: "food",
      countInStock: 10,
      size: '5kg',
      rating: 4.5,
      numReviews: 10,
      city: 'polokwane',
      province: 'limpopo',
      location: 'moletje',
      description: "Introducing our succulent oranges, nature's perfect blend of tangy sweetness and refreshing zest. Bursting with juicy flavor and vibrant color, each handpicked orange promises a delightful sensory experience. Whether enjoyed as a snack, juiced for a refreshing beverage, or incorporated into culinary creations, our premium oranges elevate any occasion with their unparalleled freshness and natural goodness. Taste the sunshine with every bite of our premium oranges.",
    },
    {
      // _id: '1',
      name: 'Sweet Potatoes',
      slug: 'sweet-potatoes',
      category: 'vegitables',
      image: "https://images.pexels.com/photos/2872755/pexels-photo-2872755.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
      price: 120,
      catalogue: "food",
      countInStock: 10,
      size: '5kg',
      rating: 4.5,
      numReviews: 10,
      city: 'polokwane',
      province: 'limpopo',
      location: 'moletje',
      description: "Introducing our succulent oranges, nature's perfect blend of tangy sweetness and refreshing zest. Bursting with juicy flavor and vibrant color, each handpicked orange promises a delightful sensory experience. Whether enjoyed as a snack, juiced for a refreshing beverage, or incorporated into culinary creations, our premium oranges elevate any occasion with their unparalleled freshness and natural goodness. Taste the sunshine with every bite of our premium oranges.",
    },
    {
      // _id: '1',
      name: 'Butternut Squash',
      slug: 'butternut-squash',
      category: 'vegitables',
      image: "https://images.pexels.com/photos/2872755/pexels-photo-2872755.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
      price: 120,
      catalogue: "food",
      countInStock: 10,
      size: '10kg',
      rating: 4.5,
      numReviews: 10,
      city: 'polokwane',
      province: 'limpopo',
      location: 'moletje',
      description: "Introducing our succulent oranges, nature's perfect blend of tangy sweetness and refreshing zest. Bursting with juicy flavor and vibrant color, each handpicked orange promises a delightful sensory experience. Whether enjoyed as a snack, juiced for a refreshing beverage, or incorporated into culinary creations, our premium oranges elevate any occasion with their unparalleled freshness and natural goodness. Taste the sunshine with every bite of our premium oranges.",
    },
    {
      // _id: '1',
      name: 'Green Beans',
      slug: 'green-beans',
      category: 'vegitables',
      image: "https://images.pexels.com/photos/2872755/pexels-photo-2872755.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
      price: 120,
      catalogue: "food",
      countInStock: 10,
      size: '10kg',
      rating: 4.5,
      numReviews: 10,
      city: 'polokwane',
      province: 'limpopo',
      location: 'moletje',
      description: "Introducing our succulent oranges, nature's perfect blend of tangy sweetness and refreshing zest. Bursting with juicy flavor and vibrant color, each handpicked orange promises a delightful sensory experience. Whether enjoyed as a snack, juiced for a refreshing beverage, or incorporated into culinary creations, our premium oranges elevate any occasion with their unparalleled freshness and natural goodness. Taste the sunshine with every bite of our premium oranges.",
    },
    {
      // _id: '1',
      name: 'Green Peppers ',
      slug: 'green-peppers ',
      category: 'vegitables',
      image: "https://images.pexels.com/photos/2872755/pexels-photo-2872755.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
      price: 120,
      catalogue: "food",
      countInStock: 10,
      size: '10kg',
      rating: 4.5,
      numReviews: 10,
      city: 'polokwane',
      province: 'limpopo',
      location: 'moletje',
      description: "Introducing our succulent oranges, nature's perfect blend of tangy sweetness and refreshing zest. Bursting with juicy flavor and vibrant color, each handpicked orange promises a delightful sensory experience. Whether enjoyed as a snack, juiced for a refreshing beverage, or incorporated into culinary creations, our premium oranges elevate any occasion with their unparalleled freshness and natural goodness. Taste the sunshine with every bite of our premium oranges.",
    },
  
  ],
};
export default data;
